# Generated by Django 3.0 on 2019-12-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semister', models.IntegerField()),
                ('Subject_name', models.CharField(max_length=30)),
                ('Subject_code', models.CharField(max_length=10)),
                ('Full_marks', models.IntegerField()),
                ('Pass_Marks', models.IntegerField()),
            ],
        ),
    ]
