# Generated by Django 3.0 on 2019-12-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Student_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Batch',
            field=models.IntegerField(null=True),
        ),
    ]
