# Generated by Django 3.0 on 2019-12-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191219_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Department',
            field=models.ManyToManyField(to='shop.Department'),
        ),
    ]
