# Generated by Django 3.0 on 2019-12-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Subject',
            field=models.ManyToManyField(to='shop.Subject'),
        ),
    ]
