# Generated by Django 3.0 on 2019-12-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Subject',
            field=models.ManyToManyField(to='shop.Subject'),
        ),
    ]
