# Generated by Django 3.0 on 2019-12-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_student_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_Morning',
            field=models.BooleanField(default=True),
        ),
    ]
