# Generated by Django 3.0 on 2019-12-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_teacher_is_morning'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Semister',
            field=models.IntegerField(null=True),
        ),
    ]
