# Generated by Django 3.0 on 2019-12-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_student_semister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Student_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_name',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
